[env:m5stickc]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_flags =
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
  -DCONFIG_BT_NIMBLE_LOG_LEVEL=0 ; Disable NimBLE debug logs
  -DCONFIG_NIMBLE_CPP_LOG_LEVEL=0 
lib_deps =
  m5stack/M5Unified@^0.1
  m5stack/M5GFX@^0.1
  m5stack/M5StickCPlus2@^1.0.2
  ; kenichi884/M5StackToio
  h2zero/NimBLE-Arduino@^1.4.1
  gilmaimon/ArduinoWebsockets@^0.5.3
  bblanchon/ArduinoJson@^7.2.0
lib_ignore =
  DFRobot_GP8XXX
